# -*- mode: ruby -*-
# vi: set ft=ruby :

# Quantidade de máquinas que irão subir
NODE_COUNT = 3
BOX_IMAGE = "generic/ubuntu2204"
VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      # Range de IP a ser utilizado e Interface de rede
      subconfig.vm.network :public_network, ip: "192.168.18.#{i + 129}", bridge: "Realtek Gaming GbE Family Controller"
      subconfig.vm.disk :disk, size: "50GB", name: "extra_storage#{i + 1}"
    end
    config.vm.provider "virtualbox" do |v|
      #Configura memória e vCPUS das máquinas
      v.memory = 1500
      v.cpus = 2
    end    
  end
  # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
    # Rota do seu gateway padrão
    apt-get install net-tools -y
    route add default gw 192.168.18.1
  SHELL
end
